app/models/contact.py
from app.extensions import db
from datetime import datetime

# Messages sent through the contact form are saved to the database using this model
# They are, however, not displayed in the admin dashboard, but this can be a further implementation.

class Blog_Contact(db.Model):
    __tablename__ = "blog_contact"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    email = db.Column(db.String(100), nullable=False)
    message = db.Column(db.String(700))

app/models/posts.py
from app.extensions import db
from datetime import datetime

class Blog_Posts(db.Model):
    __tablename__ = "blog_posts"
    id = db.Column(db.Integer, primary_key=True)
    date_submitted = db.Column(db.DateTime, default=datetime.utcnow)
    date_to_post = db.Column(db.DateTime, default=datetime.utcnow)
    title = db.Column(db.String(200), nullable=False)
    intro = db.Column(db.String(200), nullable=False)
    body = db.Column(db.Text, nullable=False)
    picture_v = db.Column(db.String(200))
    picture_v_source = db.Column(db.String(500))
    picture_h = db.Column(db.String(200))
    picture_h_source = db.Column(db.String(500))
    picture_s = db.Column(db.String(200))
    picture_s_source = db.Column(db.String(500))
    picture_alt = db.Column(db.String(200))
    meta_tag = db.Column(db.String(200))
    title_tag = db.Column(db.String(200))
    admin_approved = db.Column(db.String(5), default="FALSE")
    # featured is not being used at the moment, in the future can be used to 'feature' a post on a top modal, or similar
    featured = db.Column(db.String(5), default="FALSE")
    likes = db.relationship('Blog_Likes', backref='post')
    comments = db.relationship('Blog_Comments', backref='target_post')
    replies = db.relationship('Blog_Replies', backref='target_post')
    bookmarks = db.relationship('Blog_Bookmarks', backref='post')
    author_id = db.Column(db.Integer, db.ForeignKey('blog_user.id'))
    theme_id = db.Column(db.Integer, db.ForeignKey('blog_theme.id'))
    
    def __repr__(self):
        return f"<Post {self.id}: {self.title}, Theme: {self.theme_id}>"

app/website/forms.py
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired


class The_Comments(FlaskForm):
    comment = TextAreaField("Comment", validators=[
                            DataRequired()], widget=TextArea())
    submit = SubmitField()

app/website/routes.py
import smtplib, os, json
from flask import Blueprint, render_template, request, jsonify, make_response
from app.extensions import db
from app.website.contact import send_email
from app.models.contact import Blog_Contact
from app.models.themes import Blog_Theme
from app.models.posts import Blog_Posts
from app.models.user import Blog_User
from app.models.likes import Blog_Likes
from app.models.bookmarks import Blog_Bookmarks
from app.models.comments import Blog_Comments, Blog_Replies
from app.models.helpers import update_likes, update_bookmarks, delete_comment, delete_reply
from flask_login import current_user
from datetime import datetime
from sqlalchemy import desc
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
from os import listdir

directory_image_about = "app/static/Pictures_Liquet_About/"
directory_image_post = "app/static/Pictures_Liquet_Post/"
directory_image_theme = "app/static/Pictures_Themes/"
directory_image_home = "app/static/Best_Seller/"
directory_image_birthday_wishes = "app/static/Birthday_Wishes/"
directory_image_gallery = "app/static/Gallery"

website = Blueprint('website', __name__,
                    static_folder="../static", template_folder="../template")
load_dotenv()

# Blog website pages: Home Page, All posts, About, Contact page
# Routes available for registered and non-registered users alike

def text():
    with open("app/static/JSON/about_text.json", "r") as about_file, \
        open("app/static/JSON/title_post.json", "r") as post_file, \
        open("app/static/JSON/post.json", "r") as isi_file, \
        open("app/static/JSON/birthday_wishes.json", "r") as isi_birthday_wishes:

        about_data = json.load(about_file)
        post_data = json.load(post_file)
        isi_data = json.load(isi_file)
        birthday_wishes = json.load(isi_birthday_wishes)
        return {
            "isi_about_data" : about_data,
            "isi_post_data" : post_data,
            "isi_isi_data" : isi_data,
            "isi_isi_birthday_wishes" : birthday_wishes
        }

#ROUTE HALAMAN HOME LAMA
# @website.route("/")
# def home():
#     # query database for themes while getting picture src
#     posts_themes = [(u.theme, u.picture, u.id)
#                     for u in db.session.query(Blog_Theme).all()]
#     theme_list = [t[2] for t in posts_themes]
    
#     # query posts to get the latest 3 posts of each theme. 
#     # Important note: the code bellow is not maintainable if we increase the number of themes, but I could not achieve a better result on my own.
#     # This should be improved.
#     # The code also selects the forth theme's query results' ids to identify these posts, as this is the only group of posts displayed separately in index.html
#     posts_all = []
#     forth_theme_post_ids = []
#     for num_themes in theme_list:
#         query = db.session.query(Blog_Posts).filter(
#                 Blog_Posts.admin_approved == "TRUE", Blog_Posts.date_to_post <= datetime.utcnow(),
#             Blog_Posts.theme_id == num_themes).order_by(desc(Blog_Posts.date_to_post)).limit(3)
#         posts_all.append(query.all())
#         if num_themes == 4:
#             for this_query in query:
#                 forth_theme_post_ids.append(this_query.id)
#     posts_all = posts_all[0] + posts_all[1] + posts_all[2] + posts_all[3]

#     return render_template('website/index_lama.html', posts_all=posts_all, posts_themes=posts_themes, logged_in=current_user.is_authenticated, forth_theme_post_ids=forth_theme_post_ids)

@website.route("/")
def home():
    image_files = [
        img for img in os.listdir(directory_image_theme)
        if img.endswith(('.jpg', '.jpeg', 'png', '.gif', 'webp'))
    ]

    image_home = [
        img for img in os.listdir(directory_image_home)
        if img.endswith(('.jpg', '.jpeg', 'png', '.gif', 'webp'))
    ]

    items = [
        {
            "id" : os.path.splitext(image_files[i])[0],
            "image" : '/static/Pictures_Themes/' + image_files[i]
        }
        for i, image in enumerate(image_files)
    ]

    #jpeg untuk manik, handicraft
    #jpg untuk buket bunga dan coklat
    items_2 = [
        {
            "id" : os.path.splitext(image_home[i])[0],
            "image" : '/static/Best_Seller/' + image_home[i]
        }
        for i, image in enumerate(image_home)
    ]

    return render_template('website/index.html', hasil = items, hasil_2 = items_2)

#FUNGSI HALAMAN ALL LAMA
# route to 'All Posts' page or page by chosen theme
# @website.route("/all/<int:index>")
# def all(index):
#     index = int(index)
#     all_blog_posts = None
#     chosen_theme = ""
#     intros = []
#     if index != 0:
#         chosen_theme = db.session.query(
#             Blog_Theme).filter(Blog_Theme.id == index).first().theme
#         all_blog_posts = db.session.query(Blog_Posts).filter(Blog_Posts.theme_id == index,
#             Blog_Posts.admin_approved == "TRUE", Blog_Posts.date_to_post <= datetime.utcnow(),
#         ).order_by(desc(Blog_Posts.date_to_post)).limit(25)
#     else:
#         all_blog_posts = db.session.query(Blog_Posts).filter(
#             Blog_Posts.admin_approved == "TRUE", Blog_Posts.date_to_post <= datetime.utcnow(),
#             ).order_by(desc(Blog_Posts.date_to_post)).limit(25)
#     for post in all_blog_posts:
#         if len(post.intro) > 300:
#             cut_intro_if_too_long = f"{post.intro[:300]}..."
#             intros.append(cut_intro_if_too_long)
#         else:
#             intros.append(post.intro)

#     return render_template('website/contoh_all_post.html', all_blog_posts=all_blog_posts, chosen_theme=chosen_theme, intros=intros, logged_in=current_user.is_authenticated)

@website.route("/all_product")
def all():
    text_data = text()
    isi = []
    post_data = list(text_data.get("isi_post_data", {}).get("post", {}).values())
    for item in post_data:
        if len(item["content"]) > 150:
            cut_intro_if_too_long = f"{item["content"][:150]}..."
            isi.append(cut_intro_if_too_long)
    image_files = [
        img for img in os.listdir(directory_image_post)
        if img.endswith((".jpg", ".jpeg", ".png", ".webp"))
    ]
    
    items = [
        {
            "id" : post_data[i]["id"],
            "image" : post_data[i]["image"],
            "title" : post_data[i]["title"]
                if i < len(post_data)
                    else "Default title",
            "content" : isi[i]
                if i < len(isi)
                    else "Default content"
        }
        for i, image in enumerate(image_files)
    ]
    print(items)
    return render_template('website/all_product.html', items = items)

#FUNGSI ABOUT LAMA, UNTUK AMBIL SEMUA FOTO DI DATABASE
# @website.route("/about/")
# def about():
#     authors_all = db.session.query(Blog_User).filter(
#         Blog_User.blocked == "FALSE", Blog_User.type == "author",
#         ).order_by(desc(Blog_User.id)).limit(25)
#     return render_template('website/about.html', authors_all=authors_all, logged_in=current_user.is_authenticated)

@website.route("/about/")
def about():
    text_data = text()
    about_data = list(text_data.get("isi_about_data", {}).get("about", {}).values())
    image_files = [
        img for img in os.listdir(directory_image_about)
        if img.endswith((".jpg", ".jpeg", ".png", ".webp"))
    ]
    print('image_files : ', image_files)

    items = [
        {
            "image" : f"/static/Pictures_Liquet_About/{image}",
            "title" : about_data[i]["title"] 
                if i < len(about_data) 
                    else "Default title",
            "content" : about_data[i]["content"] 
                if i < len(about_data) 
                    else "Default content"
        }
        for i, image in enumerate(image_files)
    ]
    
    return render_template('website/about.html', items = items)  

# FUNGSI CONTACT LAMA
# @website.route("/contact/", methods=['POST', 'GET'])
# def contact():
#     if request.method == "POST":
#         contact_name = request.form['contact_name']
#         contact_email = request.form['contact_email']
#         contact_message = request.form['contact_message']
#         new_contact = Blog_Contact(
#             name=contact_name, email=contact_email, message=contact_message)
#         try:
#             # push to database:
#             db.session.add(new_contact)
#             db.session.commit()
#             # send email:
#             send_email(contact_name, contact_email, contact_message)
#             return render_template('website/contact.html', msg_sent=True, logged_in=current_user.is_authenticated)
#         except:
#             return "There was an error adding message to the database."
#     return render_template('website/contact.html', msg_sent=False, logged_in=current_user.is_authenticated)

@website.route("/contact/", methods=['POST', 'GET'])
def contact():
    if request.method == "POST":
        SMTP_Server = "smtp.gmail.com"
        SMTP_Port = 587
        SMTP_Email = os.getenv("SMTP_EMAIL")
        SMTP_Password = os.getenv("SMTP_PASSWORD")
        recipients = ["hendratmobudihardjo@gmail.com", "onggaralidya25@gmail.com"]
        contact_name = request.form['contact_name']
        contact_email = request.form['contact_email']
        contact_message = request.form['contact_message']
        try:
            message = MIMEMultipart()
            message["Reply-To"] = contact_email
            message["To"] = ", ".join(recipients)
            message["Subject"] = f"Message from {contact_name}"
            message.attach(MIMEText(contact_message, "plain"))
            s = smtplib.SMTP(SMTP_Server, SMTP_Port)
            s.starttls()
            s.login(SMTP_Email, SMTP_Password)
            s.sendmail(SMTP_Email, recipients, message.as_string())
            s.quit()
            return render_template('website/contact.html', msg_sent=True, logged_in=current_user.is_authenticated)

app/templates/website/about.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="About the Travel Blog">
{% endblock %}

{% block title %}About Us{% endblock %}

{% block content %}

    <!-- Content -->
    <h1 class="ALL-special-font ALL-h1 text-center">About Sweet Panda..</h1>

    <!-- Cards: Culture (missing piece)-->
    {% for item in items %}
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;padding:0px 20px 0px 20px;">
                <div class="col-md-6 card-img ALL-picture ">
                    <img src="{{ item.image }}" class="card-img" alt="image">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <p class="card-text text-justify">{{ item.content }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}

    <section class="mb-3 container-fluid">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;">
                <div class="col-12">
                    <hr style="border-width: 3px;">
                </div>
            </div>
        </div>
    </section>

{% endblock %}

app/templates/website/all_posts.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="Travel blog - All Posts">
{% endblock %}
{% block title %}Our Products{% endblock %}

{% block content %}
    <!-- Content -->
    <h1 class="ALL-special-font ALL-h1 text-center">Our Products</h1>

    <!-- Cards: all posts-->
    {% for item in items %}
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;">
                <div class="col-md-6 card-img ALL-picture ">
                    <img src="{{ item.image }}" class="card-img" alt="image">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <p class="card-text text-justify">{{ item.content }}</p>
                        <a role="button" href="/post/{{ item.id }}" class="btn ALL-green-btn mb-2" style="width: 150px;">Read More..</a>
                        <!-- <p class="card-text"><small class="text-muted"> Author name</small></p> -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}

    <section class="mb-3 container-fluid">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;">
                <div class="col-12">
                    <hr style="border-width: 3px;">
                </div>
            </div>
        </div>
    </section>

{% endblock %}

app/templates/website/all_product.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="Travel blog - All Posts">
{% endblock %}
{% block title %}Our Products{% endblock %}

{% block content %}
    <!-- Content -->
    <h1 class="ALL-special-font ALL-h1 text-center">Our Products</h1>

    <!-- Cards: all posts-->
    {% for item in items %}
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;padding:0px 20px 0px 20px;">
                <div class="col-md-6 card-img ALL-picture ">
                    <img src="{{ item.image }}" class="card-img" alt="image" style="height: 250px;">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <p class="card-text text-justify">{{ item.content }}</p>
                        <a role="button" href="/post/{{ item.id }}" class="btn ALL-green-btn mb-2" style="width: 150px;">Read More..</a>
                        <!-- <p class="card-text"><small class="text-muted"> Author name</small></p> -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}

    <section class="mb-3 container-fluid">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;">
                <div class="col-12">
                    <hr style="border-width: 3px;">
                </div>
            </div>
        </div>
    </section>

{% endblock %}

app/templates/website/contact.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="Travel blog - Contact">
{% endblock %}
{% block title %}Contact Us{% endblock %}

{% block content %}

<!-- Content -->
<h1 class="ALL-special-font ALL-h1 text-center">Contact Us</h1>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <p class="col-lg-8 col-md-10 text-justify">Want your very own customizable? Share your thoughts!</p>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <!-- form ini mengarah ke function contacts di website\routes.py -->
        <form class="col-lg-8 col-md-10" action="/contact" method="POST">
            <div class="form-group">
                <label for="contact_name">Name</label>
                <input type="text" class="form-control" id="contact_name" name="contact_name" placeholder="Your Name" maxlength="200" required>
            </div>
            <div class="form-group">
                <label for="contact_email">Email address</label>
                <input type="email" class="form-control" id="contact_email" name="contact_email" placeholder="name@example.com" maxlength="100" required>
            </div>
            <div class="form-group">
                <label for="contact_message">Message</label>
                <textarea class="form-control" id="contact_message" name="contact_message" rows="3" placeholder="Write your thoughts here!" maxlength="700"></textarea>
            </div>
            <button type="submit" class="btn ALL-green-btn mb-2">Submit</button>
        </form>
    </div>
</section>

{% if msg_sent == True: %}
<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <p class="ALL-msg-sent">Message sent! Thank you!</p>
        </div>
    </div>
</section>
{% endif %}

{% endblock %}

app/templates/website/contoh all_post.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="Travel blog - All Posts">
{% endblock %}
{% block title %}Our Products{% endblock %}

{% block content %}

    <!-- Content -->
    {% if chosen_theme == "": %}
    <h1 class="ALL-special-font ALL-h1 text-center">Our Products</h1>
    {% else: %}
    <h1 class="ALL-special-font ALL-h1 text-center">{{chosen_theme}}: Blog Posts</h1>
    {% endif %}

    <!-- Cards: all posts-->
    {% set i = 0 %}
    {% for post in all_blog_posts: %}
    {% set i = i + 1 %}
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;">
                <div class="col-md-6 card-img ALL-picture ">
                    <img src="{{ url_for('static', filename='Pictures_Posts/'+post.picture_h) }}" class="card-img"
                        alt="{{ post.picture_alt }}">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text text-justify">{{ intros[i] }}</p>
                        <a role="button" href="{{ url_for('website.blog_post', index=post.id) }}" class="btn ALL-green-btn mb-2" style="width: 150px;">Read</a>
                        <p class="card-text"><small class="text-muted"> by {{ post.author.name }} - {{ post.date_to_post.strftime('%d %B %Y') }}</small></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}

{% endblock %}

app/templates/website/contoh_all_post.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="Travel blog - All Posts">
{% endblock %}
{% block title %}Our Products{% endblock %}

{% block content %}

    <!-- Content -->
    {% if chosen_theme == "": %}
    <h1 class="ALL-special-font ALL-h1 text-center">Our Products</h1>
    {% else: %}
    <h1 class="ALL-special-font ALL-h1 text-center">{{chosen_theme}}: Blog Posts</h1>
    {% endif %}

    <!-- Cards: all posts-->
    {% set i = 0 %}
    {% for post in all_blog_posts: %}
    {% set i = i + 1 %}
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            <div class="row no-gutters" style="width: 57rem;">
                <div class="col-md-6 card-img ALL-picture ">
                    <img src="{{ url_for('static', filename='Pictures_Posts/'+post.picture_h) }}" class="card-img"
                        alt="{{ post.picture_alt }}">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text text-justify">{{ intros[i] }}</p>
                        <a role="button" href="{{ url_for('website.blog_post', index=post.id) }}" class="btn ALL-green-btn mb-2" style="width: 150px;">Read</a>
                        <p class="card-text"><small class="text-muted"> by {{ post.author.name }} - {{ post.date_to_post.strftime('%d %B %Y') }}</small></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}

{% endblock %}

app/templates/website/gallery.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="About the Travel Blog">
{% endblock %}

{% block title %}Gallery{% endblock %}

{% block content %}

    <!-- Content -->
    <h1 class="ALL-special-font ALL-h1 text-center">Sweet Panda Gallery</h1>

    {% for item in items[:8] %}
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            <div class="row no-gutters w-75 px-3">
                <div class="card-img ALL-picture">
                    <img src="{{ item.image }}" class="card-img" alt="image" style="width:40rem;height:40rem;border-radius:40px;object-fit:cover;">
                </div>
            </div>
        </div>
    </section>
    {% endfor %}

    <section class="mb-3 container-fluid">
        <div class="row justify-content-center">
            <div class="row no-gutters w-75 px-3">
                <div class="col-12">
                    <hr style="border-width: 3px;">
                </div>
            </div>
        </div>
    </section>

{% endblock %}

app/templates/website/index_lama.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="Travel blog - Your source of travel tips and news">
{% endblock %}
{% block title %}Sweet Panda's Handicraft{% endblock %}

{% block content %}

<!-- Content -->
    <!-- Main image -->
    <section class="container-fluid HOME-img-main">
        <h1 class="HOME-special-font HOME-title">Sweet Panda's Handicraft</h1>
        <p class="HOME-sub-title"><span>Make your very own Bouquet and Handicraft seamless..:)</span></p>
    </section>

    <!-- Cards: Themes -->
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            {% for theme in posts_themes: %}
            <div class="col col-auto mb-3 HOME-theme-btn">
                <a class="ALL-no-hover" href="{{ url_for('website.all', index=theme[2]) }}">
                    <div class="card h-100" style="width: 13rem; border:none;">
                        <img src="{{ url_for('static', filename='Pictures_Themes/'+theme[1]) }}" class="card-img-top HOME-round-img" alt="Theme" />
                        <div class="card-body" style="display:flex; justify-content: center;">
                            <h5 class="card-title ALL-no-hover">{{theme[0]}}</h5>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </section>

    <!-- Cards: Beach -->
    <section class="container-fluid">
        <div class="row justify-content-center">
            {% for beach_posts in posts_all: %}
            {% if beach_posts.theme_group.theme == posts_themes[0][0]: %}
            <div class="col col-auto mb-3">
                <a class="ALL-no-hover" href="{{ url_for('website.blog_post', index=beach_posts.id, _external=True) }}">
                    <div class="card h-100 HOME-card ALL-post-hover" style="width: 18rem;">
                        <img src="{{ url_for('static', filename='Pictures_Posts/'+beach_posts.picture_v) }}" class="card-img-top" alt="{{ beach_posts.picture_alt }}" />
                        <div class="card-body">
                            <h5 class="card-title ALL-no-hover">{{ beach_posts.title }}</h5>
                        </div>
                        <div class="card-footer HOME-card-footer">
                            <small class="text-muted ALL-no-hover">by {{ beach_posts.author.name }}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </section>

    <!-- Cards: Culture -->
    <section class="container-fluid mt-4 HOME-backg">
        <div class="row justify-content-center">
            {% for cultural in posts_all: %}
            {% if cultural.theme_group.theme == posts_themes[3][0] and cultural.id == forth_theme_post_ids[0] or cultural.id == forth_theme_post_ids[1]: %} <div class="col col-auto mb-3">
                <a class="ALL-no-hover" href="{{ url_for('website.blog_post', index=cultural.id) }}">
                    <div class="card h-100 ALL-post-hover" style="width: 27.9rem;">
                        <img src="{{ url_for('static', filename='Pictures_Posts/'+cultural.picture_h) }}" class="card-img" alt="{{ cultural.picture_alt }}" />
                        {% if cultural.id == forth_theme_post_ids[1]: %}
                        <div class="card-img-overlay d-flex flex-column justify-content-end">
                        {% else: %}
                        <div class="card-img-overlay">
                        {% endif %}
                            <h5 class="card-title HOME-txt-background ALL-no-hover">{{ cultural.title }}</h5>
                            <p class="card-text HOME-txt-background ALL-no-hover">by {{ cultural.author.name }}</p>
                        </div>
                        </div>
                    </div>
                </a>
                {% endif %}
                {% endfor %}
        </div>
    </section>

    <!-- Cards: Nature -->
    <section class="container-fluid mt-4 HOME-backg">
        <div class="row justify-content-center">
            {% for nature_posts in posts_all: %}
            {% if nature_posts.theme_group.theme == posts_themes[2][0]: %}
            <div class="col col-auto mb-3">
                <a class="ALL-no-hover" href="{{ url_for('website.blog_post', index=nature_posts.id) }}">
                    <div class="card h-100 HOME-card ALL-post-hover" style="width: 18rem;">
                        <img src="{{ url_for('static', filename='Pictures_Posts/'+nature_posts.picture_s) }}" class="card-img-top" alt="{{ nature_posts.picture_alt }}" />
                        <div class="card-body">
                            <h5 class="card-title ALL-no-hover">{{ nature_posts.title }}</h5>
                        </div>
                        <div class="card-footer HOME-card-footer">
                            <small class="text-muted">by {{ nature_posts.author.name}}</small>
                        </div>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </section>

    <!-- Cards: Culture -->
    <section class="container-fluid mt-4">
        <div class="row justify-content-center" >
            {% for cultural_post in posts_all: %}
            {% if cultural_post.theme_group.theme== posts_themes[3][0] and cultural_post.id == forth_theme_post_ids[2]: %}
            <a class="ALL-no-hover" href="{{ url_for('website.blog_post', index=cultural_post.id) }}">
                <div class="row no-gutters ALL-post-hover" style="width: 57rem;">
                    <div class="col-md-6 card-img" style="display:flex; justify-content:center;">
                        <img src="{{ url_for('static', filename='Pictures_Posts/'+cultural_post.picture_h) }}" class="card-img" alt="{{ cultural_post.picture_alt }}">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <h5 class="card-title ALL-no-hover">{{ cultural_post.title }}</h5>
                            <p class="card-text ALL-no-hover text-justify">{{ cultural_post.intro }}</p>
                            <p class="card-text ALL-no-hover"><small class="text-muted"> by {{ cultural_post.author.name }}</small></p>
                        </div>
                    </div>
                </div>
            </a>
            {% endif %}
            {% endfor %}
        </div>
    </section>

    <!-- Cards: Cities -->
    <section class="container-fluid mt-4">
        <div class="row justify-content-center">
            {% for city_posts in posts_all: %}
            {% if city_posts.theme_group.theme == posts_themes[1][0]: %}
            <a class="ALL-no-hover" href="{{ url_for('website.blog_post', index=city_posts.id) }}">
                <div class="col col-auto mb-3">
                    <div class="card h-100 HOME-card ALL-post-hover" style="width: 18rem; height: 380px !important;" >
                        <img src="{{ url_for('static', filename='Pictures_Posts/'+city_posts.picture_h) }}" class="card-img-top" alt="{{ city_posts.picture_alt }}" />
                        <div class="card-body">
                            <h5 class="card-title ALL-no-hover">{{ city_posts.title }}</h5>
                        </div>
                        <div class="card-footer HOME-card-footer">
                            <small class="text-muted ALL-no-hover">by {{ city_posts.author.name }}</small>
                        </div>
                    </div>
                </div>
            </a>
            {% endif %}
            {% endfor %}
        </div>
    </section>

{% endblock %}