app/models/posts.py
from app.extensions import db
from datetime import datetime

class Blog_Posts(db.Model):
    __tablename__ = "blog_posts"
    id = db.Column(db.Integer, primary_key=True)
    date_submitted = db.Column(db.DateTime, default=datetime.utcnow)
    date_to_post = db.Column(db.DateTime, default=datetime.utcnow)
    title = db.Column(db.String(200), nullable=False)
    intro = db.Column(db.String(200), nullable=False)
    body = db.Column(db.Text, nullable=False)
    picture_v = db.Column(db.String(200))
    picture_v_source = db.Column(db.String(500))
    picture_h = db.Column(db.String(200))
    picture_h_source = db.Column(db.String(500))
    picture_s = db.Column(db.String(200))
    picture_s_source = db.Column(db.String(500))
    picture_alt = db.Column(db.String(200))
    meta_tag = db.Column(db.String(200))
    title_tag = db.Column(db.String(200))
    admin_approved = db.Column(db.String(5), default="FALSE")
    # featured is not being used at the moment, in the future can be used to 'feature' a post on a top modal, or similar
    featured = db.Column(db.String(5), default="FALSE")
    likes = db.relationship('Blog_Likes', backref='post')
    comments = db.relationship('Blog_Comments', backref='target_post')
    replies = db.relationship('Blog_Replies', backref='target_post')
    bookmarks = db.relationship('Blog_Bookmarks', backref='post')
    author_id = db.Column(db.Integer, db.ForeignKey('blog_user.id'))
    theme_id = db.Column(db.Integer, db.ForeignKey('blog_theme.id'))
    
    def __repr__(self):
        return f"<Post {self.id}: {self.title}, Theme: {self.theme_id}>"

app/models/user.py
from app.extensions import db
from flask_login import UserMixin
from datetime import datetime

class Blog_User(UserMixin, db.Model):
    __tablename__ = "blog_user"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False, unique=True)
    email = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    about = db.Column(db.String(385), default="")
    # picture's name is saved here, but file saved in static folder
    picture = db.Column(
        db.String(), default="Picture_default.jpg")
    # type can be: admin, super_admin, author, or user
    type = db.Column(db.String(100), nullable=False, default="user")
    blocked = db.Column(db.String(5), default="FALSE")
    admin_notes = db.Column(db.Text)
    posts = db.relationship('Blog_Posts', backref='author')
    comments = db.relationship('Blog_Comments', backref='user')
    replies = db.relationship('Blog_Replies', backref='user')
    likes = db.relationship('Blog_Likes', backref='user')
    bookmarks = db.relationship('Blog_Bookmarks', backref='user')

    

    def __repr__(self):
        return f"<User: {self.id} {self.name} {self.email}>"

app/dashboard/forms.py
from datetime import datetime
from flask_wtf import FlaskForm 
from flask_wtf.file import FileField
from wtforms import StringField, SubmitField, DateTimeField, SelectField
from wtforms.validators import DataRequired
from flask_ckeditor import CKEditorField

class The_Posts(FlaskForm):
    theme = SelectField(u'Theme', coerce=int)
    author = StringField("Author")
    date = DateTimeField('Date', default=datetime.now, format='%Y-%m-%d')
    title = StringField("Title", validators=[DataRequired()])
    intro = StringField("Intro", validators=[DataRequired()])
    body = CKEditorField("Body", validators=[DataRequired()])

    picture_v = FileField("Picture Vertical")
    picture_v_source = StringField(
        "Picture Vertical Source", default="http://")
    picture_v_size = StringField("Picture File Size")

    picture_h = FileField("Picture Horizontal")
    picture_h_source = StringField(
        "Picture Horizontal Source", default="http://")
    picture_h_size = StringField("Picture File Size")

    picture_s = FileField("Picture Squared")
    picture_s_source = StringField("Picture Squared Source", default="http://")
    picture_s_size = StringField("Picture File Size")
    
    picture_alt = StringField("Picture Alt Text", validators=[DataRequired()])
    meta_tag = StringField("Meta Tag", validators=[DataRequired()])
    title_tag = StringField("Title Tag", validators=[DataRequired()])
    submit = SubmitField()

app/dashboard/routes.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, current_app
from app.extensions import db
from app.models.user import Blog_User
from app.models.posts import Blog_Posts
from app.dashboard.forms import The_Posts
from app.dashboard.helpers import check_blog_picture, delete_blog_img
from app.models.themes import Blog_Theme
from app.models.helpers import update_stats_users_active, update_approved_post_stats, change_authorship_of_all_post
from app.models.likes import Blog_Likes
from app.models.bookmarks import Blog_Bookmarks
from app.models.comments import Blog_Comments, Blog_Replies
from app.models.helpers import update_likes, update_bookmarks, delete_comment, delete_reply
from datetime import datetime
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
import os

dashboard = Blueprint('dashboard', __name__)

# Pages: dashboard, etc
# Routes available for all registered users of types admin and author

# ***********************************************************************************************
# USER MANAGEMENT: admin access only
# Managing users: see all users
@dashboard.route("/dashboard/manage_users", methods=["GET", "POST"])
@login_required
def users_table():
    user_type = current_user.type
    if user_type == "admin" or user_type == "super_admin":
        all_blog_users = Blog_User.query.order_by(Blog_User.id)
        return render_template("dashboard/users_table.html", logged_in=current_user.is_authenticated, all_blog_users=all_blog_users)
    else:
        flash("Access denied: admin access only.")
        return redirect(url_for('website.home'))

# Managing users: update user
@dashboard.route("/dashboard/manage_users/update/<int:id>", methods=["GET", "POST"])
@login_required
def user_update(id):
    acct_types = ["admin", "author", "user"]
    acct_blocked = ["FALSE", "TRUE"]
    user_to_update = Blog_User.query.get_or_404(id)

    if request.method == "POST":
        if Blog_User.query.filter(Blog_User.id != id, Blog_User.email == request.form.get("email_update")).first():
            flash("This email is already registered with us.")
            return render_template("dashboard/users_user_update.html", id=user_to_update.id, logged_in=current_user.is_authenticated, user_to_update=user_to_update, acct_types=acct_types, acct_blocked=acct_blocked)
        elif Blog_User.query.filter(Blog_User.id != id, Blog_User.name == request.form.get("username_update")).first():
            flash("This username is already registered with us.")
            return render_template("dashboard/users_user_update.html", id=user_to_update.id, logged_in=current_user.is_authenticated, user_to_update=user_to_update, acct_types=acct_types, acct_blocked=acct_blocked)
        else:
            # if the user to being updated is of type author, if type is updated, posts have to pass to default author first.
            if user_to_update.type == "author":
                if request.form.get("accttype_update") != "author":
                    change_authorship_of_all_post(user_to_update.id, 2)

            user_to_update.name = request.form.get("username_update")
            user_to_update.email = request.form.get("email_update")
            user_to_update.type = request.form.get("accttype_update")
            user_to_update.blocked = request.form.get("acctblocked_update")
            try:
                if request.form.get("acctblocked_update") == "TRUE":
                    user_comments = Blog_Comments.query.filter(
                        Blog_Comments.user_id == user_to_update.id).all()
                    user_replies = Blog_Replies.query.filter(
                        Blog_Replies.user_id == user_to_update.id).all()
                    if user_comments:
                        for comment in user_comments:
                            comment.blocked = "TRUE"
                    if user_replies:
                        for reply in user_replies:
                            reply.blocked = "TRUE"
                if request.form.get("acctblocked_update") == "FALSE":
                    user_comments = Blog_Comments.query.filter(
                        Blog_Comments.user_id == user_to_update.id).all()
                    user_replies = Blog_Replies.query.filter(
                        Blog_Replies.user_id == user_to_update.id).all()
                    if user_comments:
                        for comment in user_comments:
                            comment.blocked = "FALSE"
                    if user_replies:
                        for reply in user_replies:
                            reply.blocked = "FALSE"
                db.session.commit()
                flash("User updated successfully!")
                # no time for flash, change way of displaying success
                return redirect(url_for('dashboard.users_table'))
            except:
                db.session.rollback()
                flash("Error, try again.")
                return render_template("dashboard/users_user_update.html", id=user_to_update.id, logged_in=current_user.is_authenticated, user_to_update=user_to_update, acct_types=acct_types, acct_blocked=acct_blocked)
    else:
        return render_template("dashboard/users_user_update.html", logged_in=current_user.is_authenticated, user_to_update=user_to_update, acct_types=acct_types, acct_blocked=acct_blocked)


# Deleting user
@dashboard.route("/dashboard/manage_users/delete/<int:id>", methods=["GET", "POST"])
@login_required
def user_delete(id):
    user_to_delete = Blog_User.query.get_or_404(id)
    if request.method == "POST":
        if id == 1:
            flash("Authorization error: this user cannot be deleted")
        else:
            try:
                # if user is author, transfer the authorship of the posts to the default author
                if user_to_delete.type == "author":
                    change_authorship_of_all_post(user_to_delete.id, 2)
                # if user has comments/replies, change ownership (to default user of id 3 and delete or mark as blocked ([deleted]).
                if user_to_delete.comments:
                    comments = Blog_Comments.query.filter_by(
                        user_id=user_to_delete.id).all()
                    for comment in comments:
                        comment.user_id = 3
                        delete_comment(comment.id)
                if user_to_delete.replies:
                    replies = comments = Blog_Replies.query.filter_by(
                        user_id=user_to_delete.id).all()
                    for reply in replies:
                        reply.user_id = 3
                        delete_reply(reply.id)
                # delete bookmarks and likes
                if user_to_delete.likes:
                    likes = Blog_Likes.query.filter_by(
                        user_id=user_to_delete.id).all()
                    for like in likes:
                        db.session.delete(like)
                        update_likes(-1)
                if user_to_delete.bookmarks:
                    bookmarks = Blog_Bookmarks.query.filter_by(
                        user_id=user_to_delete.id).all()
                    for bookmark in bookmarks:
                        db.session.delete(bookmark)
                        update_bookmarks(-1)
                # delete user's picture
                if user_to_delete.picture == "" or user_to_delete.picture == "Picture_default.jpg":
                    profile_picture = None
                else:
                    profile_picture = user_to_delete.picture

                if profile_picture != None and os.path.exists(os.path.join(current_app.config["PROFILE_IMG_FOLDER"], profile_picture)):
                    os.remove(os.path.join(
                        current_app.config["PROFILE_IMG_FOLDER"], profile_picture))

                # delete user
                db.session.delete(user_to_delete)
                db.session.commit()
                flash("User deleted successfully.")
                update_stats_users_active(-1)
                return redirect(url_for('dashboard.users_table'))
            except:
                flash("There was a problem deleting this user.")
                db.session.rollback()
                return render_template("dashboard/users_user_delete.html", logged_in=current_user.is_authenticated, user_to_delete=user_to_delete)
    else:
        return render_template("dashboard/users_user_delete.html", logged_in=current_user.is_authenticated, user_to_delete=user_to_delete)

# Blocking user
# Blocking a user will not influence the stats of total active users.
# Blocked users will not be able to log in
@dashboard.route("/dashboard/manage_users/block/<int:id>", methods=["GET", "POST"])
@login_required
def user_block(id):
    user_to_block = Blog_User.query.get_or_404(id)
    if request.method == "POST":
        if id == 1:
            flash("Authorization error: this user cannot be blocked")
        else:
            user_to_block.blocked = "TRUE"
            # all comments and replies shall be blocked
            user_comments = Blog_Comments.query.filter(
                Blog_Comments.user_id == user_to_block.id).all()
            user_replies = Blog_Replies.query.filter(
                Blog_Replies.user_id == user_to_block.id).all()
            if user_comments:
                for comment in user_comments:
                    comment.blocked = "TRUE"
            if user_replies:
                for reply in user_replies:
                    reply.blocked = "TRUE"
            try:
                db.session.commit()
                flash("User blocked successfully.")
                return redirect(url_for('dashboard.users_table'))
            except:
                db.session.rollback()
                flash("There was a problem blocking this user.")

app/templates/dashboard/posts_approve_post.html
{% extends "account/dashboard_admin.html" %}
{% block page %}

<h1 class="mb-3 text-center">Approve Post</h1>
<section class="mb-3 container-fluid">
    <div class="justify-content-center">
        <p class="text-justify text-center">Approved posts will be published on the blog. This post's date is <b>{{post_to_approve.date_to_post.strftime('%d %b %Y')}}</b> and will be published under the theme <b>{{post_to_approve.theme_group.theme}}.</b></p>         
    </div>
</section>

<section class="container-fluid mt-4 mb-3">
    <div class="row justify-content-center">
        <div class="row no-gutters ALL-box-preview-shadow" style="width: 57rem;">
            <div class="col-md-6 card-img ALL-picture ">
                <img src="{{ url_for('static', filename='Pictures_Posts/'+post_to_approve.picture_h) }}" class="card-img" alt="picture of blog post">
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{post_to_approve.title}}</h5>
                    <p class="card-text text-justify">{{post_to_approve.intro}}</p>
                    <a role="button" href="{{url_for('dashboard.preview_post', id=post_to_approve.id)}}"
                        class="btn ALL-green-btn mb-2">Preview</a>
                    <p class="card-text"><small class="text-muted"> by {{ post_to_approve.author.name }} - {{ post_to_approve.date_to_post.strftime('%d %B %Y') }}</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <form class="col-lg-2 col-md-12" action="/dashboard/manage_posts/approve_post/{{post_to_approve.id}}" method="POST">
            <button type="submit" name="submit_approve" class="btn ALL-green-btn-dark mb-2" style="width:150px">Approve Post</button>
        </form>
    </div>
</section>

{% endblock %}

app/templates/dashboard/posts_delete_post.html
{% extends "account/dashboard_admin.html" %}
{% block page %}

<h1 class="mb-3 text-center">Delete Post</h1>
<section class="mb-3 container-fluid">
    <div class="justify-content-center">
        <p class="text-justify text-center">The post you are about to delete has the admin approved status of {{post_to_delete.admin_approved}}.<br>
            This post has {{ post_likes|length }} likes and {{ comments|length }} comments.
    </div>
</section>

<section class="container-fluid mt-4 mb-3">
    <div class="row justify-content-center">
        <div class="row no-gutters ALL-box-preview-shadow" style="width: 57rem;">
            <div class="col-md-6 card-img ALL-picture ">
                <img 
                {% if post_to_delete.picture_h %}
                src="{{ url_for('static', filename='Pictures_Posts/'+post_to_delete.picture_h) }}" 
                {% else %}
                src="{{ url_for('static', filename='Pictures_Posts/Picture_not_available.png') }}" 
                {% endif %}
                class="card-img" alt="picture of blog post">
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{post_to_delete.title}}</h5>
                    <p class="card-text text-justify">{{post_to_delete.intro}}</p>
                    <a role="button" href="{{url_for('dashboard.preview_post', id=post_to_delete.id)}}"
                        class="btn ALL-green-btn mb-2">Preview</a>
                    <p class="card-text"><small class="text-muted"> by {{ post_to_delete.author.name }} - {{
                            post_to_delete.date_to_post.strftime('%d %B %Y') }}</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <form class="col-lg-2 col-md-12" action="/dashboard/manage_posts/delete_post/{{post_to_delete.id}}"
            method="POST">
            <button type="submit" name="submit_delete_post" class="btn btn-danger mb-2" style="width:120px">Delete Post</button>
        </form>
    </div>
</section>

{% endblock %}

app/templates/dashboard/posts_disallow_post.html
{% extends "account/dashboard_admin.html" %}
{% block page %}

<h1 class="mb-3 text-center">Disallow Post</h1>
<section class="mb-3 container-fluid">
    <div class="justify-content-center">
        <p class="text-justify text-center">You are about to roll back the approval of this post. This post will no longer be published on the blog. This post's date is
            <b>{{post_to_disallow.date_to_post.strftime('%d %b %Y')}}</b> and would habe been published under the theme
            <b>{{post_to_disallow.theme_group.theme}}.</b></p>
    </div>
</section>

<section class="container-fluid mt-4 mb-3">
    <div class="row justify-content-center">
        <div class="row no-gutters" style="width: 57rem;">
            <div class="col-md-6 card-img ALL-picture ">
                <img src="{{ url_for('static', filename='Pictures_Posts/'+post_to_disallow.picture_h) }}" class="card-img" alt="picture of blog post">
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h5 class="card-title">{{post_to_disallow.title}}</h5>
                    <p class="card-text text-justify">{{post_to_disallow.intro}}</p>
                    <a role="button" href="{{url_for('dashboard.preview_post', id=post_to_disallow.id)}}"
                        class="btn ALL-green-btn mb-2">Preview</a>
                    <p class="card-text"><small class="text-muted"> by {{ post_to_disallow.author.name }} - {{
                            post_to_disallow.date_to_post.strftime('%d %B %Y') }}</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <form class="col-lg-2 col-md-12" action="/dashboard/manage_posts/disallow_post/{{post_to_disallow.id}}"
            method="POST">
            <button type="submit" name="submit_disallow" class="btn ALL-green-btn-dark mb-2" style="width: 150px;">Disallow
                Post</button>
        </form>
    </div>
</section>

</div>
</section>

{% endblock %}

app/templates/dashboard/posts_preview_post.html
{% extends "base.html" %}

{% block meta %}
<meta name="description" content="{{ post_to_preview.meta_tag }}">
<meta name="robots" content="noindex">
{% endblock %}

{% block title %}{{post_to_preview.title_tag}}{% endblock %}

{% block content %}

<!-- Content -->
<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10">
            <p class="ALL-special-font ALL-h1 text-center" style="margin-bottom: -20px;">in {{post_to_preview.theme_group.theme}}
            </p>
        </div>
        <div class="col-lg-8 col-md-10">
            <h1 class="text-center">{{post_to_preview.title}}</h1>
        </div>
        <div class="col-lg-8 col-md-10">
            <p class="text-center">by {{post_to_preview.author.name}} - {{post_to_preview.date_to_post.strftime('%d %b %Y')}}</p>
        </div>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <div class="row no-gutters col-12 .col-md-10" style="max-width: 57rem;">
            <div class="col-12 text-justify">
                <p>{{post_to_preview.intro}}</p>
            </div>
        </div>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <div class="row no-gutters col-12 .col-md-10"></div>
        <img class="col-12" 
            {% if post_to_preview.picture_h %}
            src="{{ url_for('static', filename='Pictures_Posts/'+post_to_preview.picture_h) }}"
            {% else %}
            src="{{ url_for('static', filename='Pictures_Posts/Picture_not_available.png') }}" 
            {% endif %}
            alt="{{post_to_preview.picture_alt}}" style="max-width: 57rem; ">
    </div>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <div class="row no-gutters col-12 .col-md-10" style="max-width: 57rem;">
            <div class="col-12 text-justify">
                {{post_to_preview.body|safe}}
            </div>
        </div>
    </div>
</section>

{% endblock %}

app/templates/dashboard/posts_submit_new.html
{% extends "account/dashboard_author.html" %}
{% block page %}
<!-- Content -->

<h1 class="mb-3 text-center">Submit new post</h1>

<section class="mb-3 container-fluid">
    <div class="justify-content-center">
        <form action="" method="POST" enctype="multipart/form-data">
            {{form.hidden_tag()}}
            {{form.theme.label (class="form-label")}}
            {{form.theme (class="form-control")}}
            <br>

            {% if current_user.type == "super_admin" %}
            {{form.author.label (class="form-label")}}
            {{form.author (class="form-control")}}
            <br>
            {% endif %}

            {{form.date.label (class="form-label")}}
            {{form.date (class="form-control", type="date")}}
            <br>
            {{form.title.label (class="form-label")}}
            {{form.title (class="form-control")}}
            <br>
            {{form.intro.label (class="form-label")}}
            {{form.intro (class="form-control")}}
            <br>
            {{form.body.label (class="form-label")}}
            {{form.body (class="form-control", rows="10")}}

            <br>
            {{form.picture_v.label (class="form-label")}}
            {{form.picture_v (class="form-control", oninput="checkFileSizeBlogPic(this, 'picture_v_size')")}}
            {{form.picture_v_size (class="form-control", id="picture_v_size", type="hidden")}}
            <br>
            {{form.picture_v_source.label (class="form-label")}}
            {{form.picture_v_source (class="form-control")}}
            <br>
            {{form.picture_h.label (class="form-label")}}
            {{form.picture_h (class="form-control", oninput="checkFileSizeBlogPic(this, 'picture_h_size')")}}
            {{form.picture_h_size (class="form-control", id="picture_h_size", type="hidden")}}
            <br>
            {{form.picture_h_source.label (class="form-label")}}
            {{form.picture_h_source (class="form-control")}}
            <br>
            {{form.picture_s.label (class="form-label")}}
            {{form.picture_s (class="form-control", oninput="checkFileSizeBlogPic(this, 'picture_s_size')")}}
            {{form.picture_s_size (class="form-control", id="picture_s_size", type="hidden")}}
            <br>
            {{form.picture_s_source.label (class="form-label")}}
            {{form.picture_s_source (class="form-control")}}
            <br>
            {{form.picture_alt.label (class="form-label")}}
            {{form.picture_alt (class="form-control")}}
            <br>
            {{form.meta_tag.label (class="form-label")}}
            {{form.meta_tag (class="form-control")}}
            <br>
            {{form.title_tag.label (class="form-label")}}
            {{form.title_tag (class="form-control")}}
            <br>
            {{form.submit(class="btn ALL-green-btn-dark mb-2")}}

        </form>
        {{ ckeditor.load(pkg_type="full") }}
        {{ ckeditor.config(name='body') }}

    </div>

</section>

{% endblock %}

app/templates/dashboard/users_table.html
{% extends "account/dashboard_admin.html" %}
{% block page %}

<h1 class="mb-3 text-center">All blog users</h1>
<section class="mb-3 container-fluid">
    <div class="table-responsive w-100">
        <table class="col-md-12 table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col"># id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Acct Type</th>
                    <th scope="col">Acct Creation</th>
                    <th scope="col">Blocked</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in all_blog_users %}
                <tr>
                    <th scope="row" class="align-middle">{{user.id}}</th>
                    <td class="align-middle">{{user.name}}</td>
                    <td class="align-middle">{{user.email}}</td>
                    <td class="align-middle">{{user.type}}</td>
                    <td class="align-middle">{{user.date_created.strftime('%d %b %Y')}}</td>
                    <td class="align-middle">{{user.blocked}}</td>
                    {% if (user.id != 1 and user.id != 2) and ((current_user.type == "super_admin") or (current_user.type == "admin" and user.type !="admin")): %}
                    <td class="d-flex flex-column h-100" style="gap: 5px;">
                        <div class="d-flex" style="gap: 5px;">
                            <a href="{{url_for('dashboard.user_preview', id=user.id)}}" target="_blank" class="btn btn-sm ALL-mini-btn"
                                style="width: 70px; background-color: #728c6996;">preview</a>
                            <a href="{{url_for('dashboard.user_update', id=user.id)}}" class="btn btn-sm ALL-mini-btn"
                                style="width: 70px; background-color: #728C69;">edit</a>
                        </div>
                        <div class="d-flex" style="gap: 5px;">
                            <a href="{{url_for('dashboard.user_block', id=user.id)}}" class="btn btn-secondary btn-sm"
                                style="width: 70px !important;">block</a>
                            <a href="{{url_for('dashboard.user_delete', id=user.id)}}" class="btn btn-danger btn-sm" style="width: 70px;">delete</a>
                        </div>
                    </td>
                    {% else: %}
                    <td class="align-middle"></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>

{% endblock %}

app/templates/dashboard/users_user_update.html
{% extends "account/dashboard_admin.html" %}
{% block page %}

<h1 class="mb-3 text-center">Update user</h1>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <p class="text-justify">You are about to change the following user:</p>
    </div>
</section>

<section class="mb-3 container-fluid">
    <div class="row justify-content-center">
        <form class="col-lg-8 col-md-10" action="{{url_for('dashboard.user_update',id=user_to_update.id)}}"
            method="POST">
            <div class="form-group">
                <label for="username_update">Username</label>
                <input type="text" class="form-control" id="username_update" name="username_update"
                    value="{{user_to_update.name}}" maxlength="200" required>
            </div>
            <div class="form-group">
                <label for="email_update">Email address</label>
                <input type="email" class="form-control" id="email_update" name="email_update"
                    value="{{user_to_update.email}}" maxlength="200" required>
            </div>
            <div class="form-group">
                <label for="accttype_update"> Acct Type </label>
                <select id="accttype_update" name="accttype_update" class="form-control">
                    {% for type in acct_types: %}
                    {% if type == user_to_update.type: %}
                    <option value="{{type}}" selected="selected">
                        {% else: %}
                    <option value="{{type}}">
                        {% endif %}
                        {{type}}
                    </option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="acctblocked_update">Blocked</label>
                <select id="acctblocked_update" name="acctblocked_update" class="form-control">
                    {% for TorF in acct_blocked: %}
                    {% if TorF == user_to_update.blocked: %}
                    <option value="{{TorF}}" selected="selected">
                        {% else: %}
                    <option value="{{TorF}}">
                        {% endif %}
                        {{TorF}}
                    </option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" name="submit_update" class="btn ALL-green-btn-dark mb-2" style="width: 150px; background-color: #728C69;">Save Changes</button>
        </form>
    </div>
</section>

</div>
</section>

{% endblock %}